[tool.poetry]
name = "network_control_rl"
version = "1.0.0"
description = "Controlling complex (directed) networks using Reinforcement Learning frameworks"
authors = ["Matej Kerekrety <matej.kerekrety@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.2"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pytest = "^7.0.1"
black = "^22.1.0"
mypy = "^0.931"
bandit = "^1.7.3"
pytest-cov = "^3.0.0"
notebook = "^6.4.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
